### PR TITLE
Utilise two workers on Travis

### PR DESCRIPTION
**Pull request by janisozaur**
Travis CI offers ~2 cores to each worker, this makes use of both of them.

### CODE REVIEW

**Comment by janisozaur** [comment]
See https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments

**Comment by jcrada** [comment]
Thanks. I just experimented with `-j2` and the difference in time is remarkable. 
Instead of modifying `.travis`, can you add `-j2` directly into the `build.sh` script for both `release` and `debug` configs?

**Comment by janisozaur** [comment]
I specifically wanted to avoid that, seeing how you advise to build using those scripts: https://github.com/fuzzylite/fuzzylite#unix. It is not considered a good practice enabling that option, unless user requested it himself.

**Comment by jcrada** [comment]
Alright, but then I am not keen on introducing another variable in travis and in the build script just for the sake of saving `travis` one minute of building time. I am definitely more interested in saving time for docker by creating an image with all the compilers, but I expect this will require too much time that I do not actually have.

**Pull request closed without merging**
