### PR TITLE
Moved template definitions in header files (reloaded)

### PR DESCRIPTION
**Pull request by sguazt**
Hi Juan,

I've moved template defs into separate `.tpp` header files (for the record, see pull request #22 ).

On Linux x86_64 with GCC 4.9.2, all compiles fine.

Also, as I previously said:

> Note, files `src/factory/ConstructionFactory.cpp and src/factory/CloningFactory.cpp`, in principle, could be removed. I'ven't done it by myself since I would have to change `cmake` files. But, unfortunately, I'm not familiar with `cmake`...

Let me know if there are other changes to do.

Cheers,

Marco

### CODE REVIEW

**Comment by jcrada** [comment]
Hi Marco,

thanks again for your collaboration. I will try to merge this commit some time next week. I am unsure about some bits, and I am thinking of some other bits I want to try out.

Cheers.

**Comment by sguazt** [comment]
Good!
Thank you for sharing fuzzylite.

Cheers,

Marco

**Comment by jcrada** [comment]
Hi Marco,

I will not merge this pull request to master because I prefer to leave these changes for version 6.0. 
More importantly, I am still not completely convinced on all these changes. I am thinking of getting rid of the <T> create methods in the terms. I will check the options we have and see how I feel about it.

Thanks.

**Comment by jcrada** [comment]
Hi Marco,

Please check the changes I have committed to the "develop" branch addressing your suggestions on this pull request. I have opted to use one of the methods you suggested instead of the ".tpp" approach I initially preferred. 

Thank you very much for your collaboration.

Cheers.

**Comment by sguazt** [comment]
Hi Juan,

Thank you for the merge.

So, now that there is a `develop` branch I will move my current changes to it and continue to work on this branch.

Cheer,

Marco

**Comment by jcrada** [comment]
Hi Marco,

yes, `master` contains a stable release (v5.0 as of now). `develop` contains the development of new features and future version 6.0.

**Pull request closed without merging**
