### PR TITLE
add Android support & remove duplicate line in FL_SOURCES

### PR DESCRIPTION
**Pull request by 9468305**
Add Android NDK standard makefile and buildscript.
Add Android test case.
Build Android shared library success.
Test success by Nexus5, AndroidL 5.1.
Remove duplicate line in FL_SOURCES (Line 2 vs Line 4).

### CODE REVIEW

**Comment by jcrada** [comment]
Thank you very much for your collaboration.

**Comment by jcrada** [comment]
Could you please provide a `README.md` file where you point out all the necessary steps and files to download and install in order to test your contribution? I really need these to test your contribution. Also, it would be great if you add a file named `AUTHOR` to the directory attributing this contribution to yourself, if you are interested. Thanks again.

**Comment by jcrada** [comment]
Apologies, but I have hard resetted the repository to the revision previous to merging the pull request. I will be happy to accept a pull request subject to the necessary instructions for me to test your contribution. Cheers.

**Comment by 9468305** [comment]
Sure. I will add it soon.

**Pull request merged**
