### PR TITLE
Fix #85 and #87: FL_LOG, FL_BUILD_PATH, and examples

### LINKED ISSUE #85: test hardcodes path
Hi,

in `fuzzylite/test/BenchmarkTest.cpp` the path to the test data is hardcoded as `../../examples/` this will break the test if they are not run from a path two levels deeper into the source than the `examples` directory. CMake supports out-of-source builds and if the "wrong" path is picked, then running the tests will fail.

This for example fails under Debian where CMake projects are by default built inside a subdirectory of the toplevel directory.

### PR DESCRIPTION
**Pull request by jcrada**

### CODE REVIEW

**Comment by jcrada** [comment]
Hi @josch. Do these changes look good to address your requests of #85 and #87? Thanks!

**Comment by josch** [comment]
Hard to say. It doesn't apply to the last release because file locations (of fuzzylite.h) and indentation changed too much. Maybe just release and I'll file follow-up bugs in case something is still amiss?

I have one comment just from reading the code: I do not think finding the leftmost "fuzzylite" is the correct solution. You should find the rightmost "fuzzylite" or otherwise this will not work if fuzzylite is built inside a path that itself contains the string "fuzzylite".

**Comment by josch** [comment]
Hi, just a friendly ping for this pull request. Could you make a new release so that I can test the current development status as a Debian package? Thanks!

**Comment by jcrada** [comment]
HI @josch. Thanks! I will focus on this during the December holidays, planning to advance lots. Maybe also undo the file formatting and leave it for last so it has a cleaner git history.

**Pull request closed without merging**
